// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyEbO3FF06e4gr7zLiAhP961FfVq-lMA8',
    appId: '1:108223842070:ios:9558f6406d2f2bfb4bb237',
    messagingSenderId: '108223842070',
    projectId: 'functionstesteluis',
    storageBucket: 'functionstesteluis.firebasestorage.app',
    iosBundleId: 'com.example.rpgGame',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhf0n-yxuFcxr36X2mh9qXKPAlYTcq6IQ',
    appId: '1:108223842070:web:58b68d6ea0c7991e4bb237',
    messagingSenderId: '108223842070',
    projectId: 'functionstesteluis',
    authDomain: 'functionstesteluis.firebaseapp.com',
    storageBucket: 'functionstesteluis.firebasestorage.app',
    measurementId: 'G-V0B4M29MQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE2foyrH_3EE72_VzPtlwKE0zV1dMFvCo',
    appId: '1:108223842070:android:7c248bc9261ca9104bb237',
    messagingSenderId: '108223842070',
    projectId: 'functionstesteluis',
    storageBucket: 'functionstesteluis.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhf0n-yxuFcxr36X2mh9qXKPAlYTcq6IQ',
    appId: '1:108223842070:web:b132c5be1d13e9ea4bb237',
    messagingSenderId: '108223842070',
    projectId: 'functionstesteluis',
    authDomain: 'functionstesteluis.firebaseapp.com',
    storageBucket: 'functionstesteluis.firebasestorage.app',
    measurementId: 'G-6DSYL0HREJ',
  );

}